---
    - name: Download Node Exporter
      get_url:
        url: "https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.linux-amd64.tar.gz"
        dest: /tmp/node_exporter-1.3.1.linux-amd64.tar.gz

    - name: Extract Node Exporter
      unarchive:
        src: /tmp/node_exporter-1.3.1.linux-amd64.tar.gz
        dest: /tmp/
        remote_src: yes

    - name: Copy Node Exporter binary to /usr/local/bin
      copy:
        src: /tmp/node_exporter-1.3.1.linux-amd64/node_exporter
        dest: /usr/local/bin/node_exporter
        mode: '0755'
        remote_src: yes

    - name: Remove downloaded archive
      file:
        path: /tmp/node_exporter-1.3.1.linux-amd64.tar.gz
        state: absent
        
    - name: Remove extracted directory
      file:
        path: /tmp/node_exporter-1.3.1.linux-amd64
        state: absent

    - name: Create node_exporter user
      user:
        name: node_exporter
        shell: /bin/false
        system: yes
        create_home: no

    - name: Change ownership of Node Exporter binary
      file:
        path: /usr/local/bin/node_exporter
        owner: node_exporter
        group: node_exporter
        
    - name: install unit file to systemd
      template:
        src: templates/node_exporter.service.j2
        dest: /etc/systemd/system/node_exporter.service
        owner: root
        group: root
        mode: 0600

    - name: Reload systemd daemon
      command: systemctl daemon-reload

    - name: Enable and start Node Exporter service
      systemd:
        name: node_exporter
        enabled: yes
        state: started

    - name: Allow port 9100 through UFW
      ufw:
        rule: allow
        port: '9100'
        proto: tcp