---
- name: Ensure the directory exists
  file:
    path: /tmp/jfrog-distribution-artifact
    state: directory
    mode: "0755"

- name: Download artifact from JFrog
  uri:
    url: "https://jfrog.iguana-devops.pp.ua/artifactory/maven-repository/citizen-jenkins-artifact-71.war"
    method: GET
    user: "{{ jfrog_username }}"
    password: "{{ jfrog_password }}"
    force_basic_auth: yes
    dest: "/tmp/jfrog-distribution-artifact/citizen-jenkins-artifact-71.war"

- name: Copy WAR file to Tomcat webapps directory
  shell: cp /tmp/jfrog-distribution-artifact/citizen-jenkins-artifact-71.war /var/lib/tomcat9/webapps/citizen.war

- name: Start and enable Tomcat service
  service:
    name: tomcat9
    state: started
    enabled: yes

- name: Remove the JFrog artifact directory
  file:
    path: /tmp/jfrog-distribution-artifact
    state: absent
    force: yes

