---
- name: Check the directory exists
  file:
    path: /tmp/jfrog-distribution-artifact
    state: directory
    mode: "0755"

- name: Construct artifact URL
  set_fact:
    latest_artifact_url: "https://jfrog.iguana-devops.pp.ua/artifactory/{{ latest_artifact_uri }}"

- name: Download the latest artifact
  uri:
    url: "{{ latest_artifact_url }}"
    method: GET
    user: "{{ jfrog_username }}"
    password: "{{ jfrog_password }}"
    force_basic_auth: yes
    dest: "/tmp/jfrog-distribution-artifact/latest-artifact.war"

- name: Copy WAR file to Tomcat webapps directory
  shell: cp /tmp/jfrog-distribution-artifact/latest-artifact.war /var/lib/tomcat9/webapps/citizen.war

- name: Start and enable Tomcat service
  service:
    name: tomcat9
    state: started
    enabled: yes

- name: Remove the JFrog artifact directory
  file:
    path: /tmp/jfrog-distribution-artifact
    state: absent
    force: yes
