---      
    - name: Update apt-repository
      apt:
        update_cache: yes

    - name: Create group for prometheus
      group:
        name: prometheus
        system: yes

    - name: Create user for prometheus
      user:
        name: prometheus
        shell: /sbin/nologin
        system: yes
        group: prometheus

    - name: Create directories for Prometheus
      file:
        path: "{{ item }}"
        state: directory
        owner: prometheus
        group: prometheus
        mode: '0755'
      loop:
        - /etc/prometheus
        - /var/lib/prometheus

    - name: Download Prometheus tarball
      get_url:
        url: https://github.com/prometheus/prometheus/releases/download/v2.43.0/prometheus-2.43.0.linux-amd64.tar.gz
        dest: /tmp/prometheus-2.43.0.linux-amd64.tar.gz

    - name: Extract Prometheus tarball
      unarchive:
        src: /tmp/prometheus-2.43.0.linux-amd64.tar.gz
        dest: /tmp/
        remote_src: yes

    - name: Move Prometheus binary
      command: mv /tmp/prometheus-2.43.0.linux-amd64/prometheus /usr/local/bin/
      args:
        creates: /usr/local/bin/prometheus

    - name: Move promtool binary
      command: mv /tmp/prometheus-2.43.0.linux-amd64/promtool /usr/local/bin/
      args:
        creates: /usr/local/bin/promtool

    - name: Change ownership of Prometheus binaries
      file:
        path: "{{ item }}"
        owner: prometheus
        group: prometheus
        state: file
        mode: '0755'
      loop:
        - /usr/local/bin/prometheus
        - /usr/local/bin/promtool
        
    - name: Configure Prometheus by using template
      template:
        src: templates/prometheus.yml.j2
        dest: /etc/prometheus/prometheus.yml
        owner: prometheus
        group: prometheus
        mode: '0644'

    - name: Create Prometheus systemd service file using template
      template:
        src: templates/prometheus.service.j2
        dest: /etc/systemd/system/prometheus.service
        owner: root
        group: root
        mode: '0644'

    - name: Move configuration files
      command: mv /tmp/prometheus-2.43.0.linux-amd64/{consoles,console_libraries,prometheus.yml} /etc/prometheus/
      args:
        creates: /etc/prometheus/prometheus.yml

    - name: Change ownership of Prometheus configuration files
      file:
        path: "{{ item }}"
        owner: prometheus
        group: prometheus
        state: directory
        recurse: yes
      loop:
        - /etc/prometheus
        - /var/lib/prometheus

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Enable Prometheus service
      systemd:
        name: prometheus
        enabled: yes

    - name: Start service
      systemd:
        name: prometheus
        state: started


