config:
  APP_NAME: "Gitea: Git with a cup of tea"
  RUN_MODE: dev
  
  database:
    DB_TYPE: 
    HOST: 
    NAME: 
    USER: 
    PASSWD: 

gitea:
  admin:
    existingSecret:
    username: 
    password: 
    email: 


persistence:
  size: 20Gi

resources:
  limits:
    cpu: 500m
    memory: 500Mi
  requests:
    cpu: 250m
    memory: 250Mi
